type Member{
    id: String!
    projectId: String!
    userId: String!
    role: String
    createdAt: Date
    deletedAt: Date
    updatedAt: Date

}

enum MemberOrder{
 role_DESC
 role_ASC
}

type MemberReponsive{
    success:Boolean
    message:String
    member:Member
}

type Query{
    findAllMembers(first: Int, skip: Int, orderBy: MemberOrder):[Member]
    findOneMember(id:String):Member
}

type Mutation{
    createdMember(
        projectId:String,
        userId:String,
        role:String
    ):MemberReponsive
    updatedMember(
        id:String!,
        projectId:String,
        userId:String,
    ):MemberReponsive
    deleteMember(
        id:String!
    ):MemberReponsive
}